### ISSUE TITLE
Says Object not found for every image

### ISSUE THREAD

**Issue by Benzidrine** [VladimirSinitsin/labelme_converter#1]
I have a freshly made labelme dataset with one object labelled called Tire and using this converter just has 
Object in 14_19_l.jpg Tire not found!

For every image. Doesn't seem like it works at all.

**Comment by VladimirSinitsin** [comment]
@Benzidrine 
Hi! 
Could you please write the structure of your dataset? I have been testing this project and also use it myself sometimes for conversion, so it should work. Regards

**Comment by VladimirSinitsin** [comment]
@Benzidrine 
And could you send at least one more example of the content of your json file. Thank you

**Comment by Benzidrine** [comment]
I get why there was an issue now. I had labelme set to not save image data in the JSON. Apologies for using your time. Thanks for your work on this.
